package insilico.daphnia_demetra.descriptors;

import insilico.core.molecule.InsilicoMolecule;
import org.openscience.cdk.CDKConstants;
import org.openscience.cdk.RingSet;
import org.openscience.cdk.aromaticity.AromaticityCalculator;
import org.openscience.cdk.graph.PathTools;
import org.openscience.cdk.graph.matrix.ConnectionMatrix;
import org.openscience.cdk.interfaces.IAtom;
import org.openscience.cdk.interfaces.IAtomContainer;
import org.openscience.cdk.interfaces.IRing;

import java.util.List;

public class MLogPdrgw {

    // This MLogP descriptor is modified in order to be consistent with
    // the MLogP values generated by DragonWeb

    public double LogP;

    private double[][] ConnMatrix;
    private int [][] TopoMatrix;
    private int nAtoms;
    private RingSet MolRings;
    private boolean[] VisitedForPRX;

    public MLogPdrgw() {
        LogP = -999;
    }

    public void Calculate(InsilicoMolecule Mol) throws Exception {

        double CX = 0;
        int NO = 0;
        int PRX = 0;
        int UB = 0;
        int HB = 0;
        int POL = 0;
        double AMP = 0;
        int ALK = 0;
        int RNG = 0;
        double QN = 0;
        int NO2 = 0;
        double NCS = 0;
        int BLM = 0;
        LogP = 0;

        IAtomContainer mol = Mol.GetStructure();
        MolRings = Mol.GetSSSR();
        TopoMatrix = Mol.GetMatrixTopologicalDistance();

        // Original CDK Matrix
        ConnMatrix = GetConnectionMatrix(mol, false, true);

        // Now we use the VEGA connection matrix where aromatic bonds
//        // are set as 1.5, previous matrix did not correctly handle
//        // aromatic bonds and resulted in inconsitent values for the same
//        // input (explicit aromatic bonds vs kekule structures)
//        ConnMatrix = Mol.GetMatrixConnectionAugmented();

        nAtoms = mol.getAtomCount();

        VisitedForPRX = new boolean[nAtoms];
        for(int i = 0; i < nAtoms; i++)
            VisitedForPRX[i] = false;

        POL = Calculate_POL(mol);
        RNG = Calculate_RNG(mol);
        ALK = Calculate_ALK(mol);
        AMP = Calculate_AMP(mol);

        for (int i = 0; i < nAtoms; i++) {

            // Counting on bonds
            for (int j = i; j < nAtoms; j++) {
                if ( (ConnMatrix[i][j] == 2)||(ConnMatrix[i][j] == 3) )
                    UB++;
            }

            // Checks on single atom type
            if (mol.getAtom(i).getSymbol().equalsIgnoreCase("C")) {
                CX++;
                continue;
            }

            if (mol.getAtom(i).getSymbol().equalsIgnoreCase("O")) {

                NO++;
                PRX += Check_PRX(mol, i);
                if (HB == 0)
                    HB = Check_HB(mol, i);

                continue;
            }

            if (mol.getAtom(i).getSymbol().equalsIgnoreCase("N")) {

                NO++;
                PRX += Check_PRX(mol, i);

                // Checks for NO2 for UB and >N< for QN and NO2
                int CountOdbl =0 ;
                int CountOsingle = 0;
                int CountBonds = 0;
                for (int j = 0; j <nAtoms; j++) {
                    if ( (AreEqual(GetName(mol,j),"O")) && (ConnMatrix[i][j] == 1) )
                        CountOsingle++;
                    if ( (AreEqual(GetName(mol,j),"O")) && (ConnMatrix[i][j] == 2) )
                        CountOdbl++;
                    if (ConnMatrix[i][j]>0)
                        CountBonds++;
                }
                if (CountOdbl == 2)
                    UB -= 2;
                if (CountBonds == 4) {
                    if (CountOsingle > 0)
                        QN += 0.5;
                    else
                        QN += 1;
                }
                if ( (CountOdbl + CountOsingle) == 2)
                    NO2++;

                if (HB == 0)
                    HB = Check_HB(mol, i);

                if (BLM == 0)
                    BLM = Check_BLM(mol, i);

                continue;
            }

            if (mol.getAtom(i).getSymbol().equalsIgnoreCase("S")) {
//                NCS += Check_NCS(mol, i);

                // todo ??
                continue;
            }

            if (mol.getAtom(i).getSymbol().equalsIgnoreCase("F")) {
                CX += 0.5;
                continue;
            }

            if (mol.getAtom(i).getSymbol().equalsIgnoreCase("Cl")) {
                CX++;
                continue;
            }

            if (mol.getAtom(i).getSymbol().equalsIgnoreCase("Br")) {
                CX += 1.5;
                continue;
            }

            if (mol.getAtom(i).getSymbol().equalsIgnoreCase("I")) {
                CX += 2;

            }

        }

        // Calculation of LogP
        LogP = -1.041 + 1.244 * Math.pow(CX,0.6) - 1.017 * Math.pow(NO, 0.9) +
                0.406 * PRX + -0.145 * Math.pow(UB, 0.8) + 0.511 * HB +
                0.268 * POL - 2.215 * AMP + 0.912 * ALK -0.392 * RNG -
                3.684 * QN + 0.474 * NO2 + 1.582 * NCS + 0.773 * BLM;

    }





    private int Check_PRX(IAtomContainer mol, int atom){

        int count=0;

        if (!( (AreEqual(GetName(mol, atom),"O")) || (AreEqual(GetName(mol, atom),"N")) ))
            return 0;

        if (VisitedForPRX[atom])
            return 0;

        VisitedForPRX[atom] = true;

        for (int i=0; i<nAtoms; i++) {

            if ( (i==atom) )
//            if ( (i==atom) || (VisitedForPRX[i]==true) )
                continue;

            // X-Y
            if ((TopoMatrix[i][atom]==1) &&
                    ((AreEqual(GetName(mol,i),"O"))||(AreEqual(GetName(mol,i),"N")))) {
                count+=2;

                // check for correction
                if ((AreEqual(GetName(mol,i),"O"))&&(AreEqual(GetName(mol,atom),"N"))&&
                        (ConnMatrix[atom][i]==1)) {
                    // O-N
                    for (int z=0; z<nAtoms; z++) {
                        if ((z==atom)||(z==i)) continue;
                        if (ConnMatrix[z][i]==1) {
                            // C-O-N
                            count--;
                            break;
                        }
                    }
                }
                if ((AreEqual(GetName(mol,i),"N"))&&(AreEqual(GetName(mol,atom),"O"))&&
                        (ConnMatrix[atom][i]==1)) {
                    // N-O
                    for (int z=0; z<nAtoms; z++) {
                        if ((z==atom)||(z==i)) continue;
                        if (ConnMatrix[z][atom]==1) {
                            // N-O-C
                            count--;
                            break;
                        }
                    }
                }

                VisitedForPRX[i] = true;
            }

            // X-A-Y
            if ((TopoMatrix[i][atom]==2) &&
                    ((AreEqual(GetName(mol,i),"O"))||(AreEqual(GetName(mol,i),"N")))) {

                List<IAtom> Path = PathTools.getShortestPath(mol, mol.getAtom(atom), mol.getAtom(i));
                String A_Atom = Path.get(1).getSymbol();
                if ((AreEqual(A_Atom,"C"))||(AreEqual(A_Atom,"S"))||(AreEqual(A_Atom,"P"))) {
                    count++;

                    // adjust to be consistent with Dragon MLogP
                    // if at least one bond is double, count is increased again
                    // except in case of O=X-N and of N=C-N
                    int MidAtom = mol.indexOf(Path.get(1));
                    if ( (ConnMatrix[MidAtom][atom]>1)||(ConnMatrix[MidAtom][i]>1) ) {
                        boolean skip = false;
                        if ((AreEqual(GetName(mol,i),"O"))&&((ConnMatrix[MidAtom][i]>1))&&
                                (AreEqual(GetName(mol,atom),"N"))&&((ConnMatrix[MidAtom][atom]==1)))
                            skip = true;
                        if ((AreEqual(GetName(mol,atom),"O"))&&((ConnMatrix[MidAtom][atom]>1))&&
                                (AreEqual(GetName(mol,i),"N"))&&((ConnMatrix[MidAtom][i]==1)))
                            skip = true;
                        if (!(skip))
                            count++;
                    }

                    VisitedForPRX[i] = true;
                }
            }
        }

        //
        // TODO
        // mancano correction -CON< e -SO2N<
        //

        return count;
    }

    private int Check_HB(IAtomContainer mol, int atom) {
        boolean isOHorNH2 = false;

        for (int i=0; i<nAtoms; i++) {
            if (i==atom)
                continue;

            if (ConnMatrix[i][atom]>0) {
                if ( (ConnMatrix[i][atom]==1) && (!isOHorNH2) )
                    isOHorNH2 = true;
                else
                    isOHorNH2 = false;
            }
        }

        if (!isOHorNH2)
            return 0;

        for (int i=0; i<nAtoms; i++) {

            if (i==atom)
                continue;

            if ( (TopoMatrix[i][atom] == 1) && (mol.getAtom(i).getFlag(CDKConstants.ISAROMATIC)) ) {
                for (int j=0; j<nAtoms; j++) {
                    if ( (TopoMatrix[atom][j] == 3) && (TopoMatrix[atom][j] == 4) )
                        if ((AreEqual(GetName(mol,j),"O"))||(AreEqual(GetName(mol,j),"N")))
                            return 1;
                }
            }
        }

        return 0;
    }

    private double Check_NCS(IAtomContainer mol, int atom) {

        // Starting from S atom

        for (int i=0; i<nAtoms; i++) {
            if (i==atom) continue;
            if ( (ConnMatrix[i][atom]>0) && (AreEqual(GetName(mol,i),"C")) ) {
                for (int j=0; j<nAtoms; j++) {
                    if (j==i) continue;
                    if (AreEqual(GetName(mol,j),"N")) {
                        if (ConnMatrix[i][j]==2)
                            return 1;       // -N=C=S
                        if (ConnMatrix[i][j]==3)
                            return 0.5;     // N#C-S-
                    }
                }
            }
        }

        return 0;
    }

    private int Check_BLM(IAtomContainer mol, int atom) {

        // Starting from N atom

        if (MolRings.contains(mol.getAtom(atom))) {
//            IRing R = (IRing)MolRings.getRings(mol.getAtom(atom)).getAtomContainer(0);
            for (IAtomContainer ac : MolRings.getRings(mol.getAtom(atom)).atomContainers() )  {
                IRing R = (IRing)ac;
                if (R.getAtomCount()==4) {
                    int N=0, C=0, CdblO=0, Other=0;
                    for (int i=0; i<4; i++) {
                        if (AreEqual(R.getAtom(i).getSymbol(),"N"))
                            N++;
                        else if (AreEqual(R.getAtom(i).getSymbol(),"C")) {
                            C++;
                            for (int k=0; k<nAtoms; k++)
                                if ( (AreEqual(GetName(mol,k),"O")) && (ConnMatrix[mol.indexOf(R.getAtom(i))][k]==2) ) {
                                    CdblO++;
                                }
                        } else
                            Other++;
                    }
                    if ( (N==1) && (C==3) && (CdblO==1) )
                        return 1;
                }
            }

        }

        return 0;
    }

    private int Calculate_POL(IAtomContainer mol) {

        int count = 0;

        for (int i=0; i<MolRings.getAtomContainerCount(); i++) {
            IRing R = (IRing) MolRings.getAtomContainer(i);
            if (AromaticityCalculator.isAromatic(R, mol))
                for (int j=0; j<R.getAtomCount(); j++) {

                    int jj = mol.indexOf(R.getAtom(j));

                    for (int k=0; k<nAtoms; k++)
                        if ( (TopoMatrix[k][jj]==1) && (!(R.contains(mol.getAtom(k)))) &&
                                (!(MolRings.contains(mol.getAtom(k)))) ) {

                            boolean RootIsC=false, ChainLongerThan2=false;
                            int Other=0, sC=0, dC=0;

                            if (AreEqual(GetName(mol,k),"C"))
                                RootIsC = true;

                            for (int z=0; z<nAtoms; z++)
                                if (TopoMatrix[k][z]==1) {

                                    if (AreEqual(GetName(mol,z),"C")) {
                                        if (ConnMatrix[k][z]==1) sC++;
                                        else if (ConnMatrix[k][z]==2) dC++;
                                        else Other++;
                                    } else {
                                        Other++;
                                    }
                                }

                            boolean toSkip = false;

                            // skip excluded substituents
                            if (RootIsC) {
                                if ((Other==1)&&(dC==0)) toSkip = true;
                                if ((Other==0)&&(sC>0)&&(dC==0)) toSkip = true;
                                if ((Other==0)&&(dC==1)) toSkip = true;
                            }

                            if (!(toSkip)) {
                                count++;
                                if (count==4)
                                    return count;
                                break;
                            }

                        }

                }
        }

        return count;
    }

    private int Calculate_RNG(IAtomContainer mol) {

        for (int i=0; i<MolRings.getAtomContainerCount(); i++) {

            IRing R = (IRing)MolRings.getAtomContainer(i);
            boolean SkipRing = false;

            // Skips benzene
            if (R.getAtomCount()==6) {
                SkipRing = true;
                for (int j=0; j<R.getAtomCount(); j++)
                    if (!(AreEqual(R.getAtom(j).getSymbol(),"C")))
                        SkipRing = false;
            }

            if (!SkipRing)
                return 1;
        }

        return 0;
    }

    private int Calculate_ALK(IAtomContainer mol) {

        int count = 0;
        boolean OnlyC;
        int C=0;

        // Check if it is a hydrocarbon compound
        OnlyC = true;
        for (int i=0; i<nAtoms; i++) {
            if  (AreEqual(GetName(mol,i),"C"))
                C++;
            else
                OnlyC = false;
        }


        return 0;
    }

    private int Calculate_AMP(IAtomContainer mol) {

        int count = 0;

        // Checks for COOH
        for (int i=0; i<nAtoms; i++) {

            boolean isC_COOH = false;
            if (!(AreEqual(GetName(mol,i),"C")))
                for (int j=0; j<nAtoms; j++) {
                    if ( (AreEqual(GetName(mol,j),"C")) && (ConnMatrix[i][j]==1) ) {
                        int Osingle=0, Odbl=0;
                        for (int k=0; k<nAtoms; k++) {
                            if ( (AreEqual(GetName(mol,k),"O")) && (ConnMatrix[j][k]==1) )
                                Osingle++;
                            if ( (AreEqual(GetName(mol,k),"O")) && (ConnMatrix[j][k]==2) )
                                Odbl++;
                        }
                        if ( (Osingle==1) && (Odbl==1) )
                            isC_COOH = true;
                    }
                }

            if (isC_COOH) {

                Boolean Pyridine=false, Amine=false;

                if (MolRings.contains(mol.getAtom(i))) {

                    // C atom is in ring, checks for Pyridine or aminobenzoic

                    boolean InvalidStruct = false;
                    IRing R = (IRing)MolRings.getRings(mol.getAtom(i)).getAtomContainer(0);
                    if ( (R.getAtomCount()==6) && (AromaticityCalculator.isAromatic(R, mol)) ) {
                        for (int j=0; j<6; j++) {
                            int Branches = 0;
                            int atomNum = mol.getAtomNumber(R.getAtom(j));
                            if (atomNum!=i) {
                                if (AreEqual(GetName(mol,j),"C")) {
                                    for (int k=0; k<nAtoms; k++) {
                                        if ( (ConnMatrix[k][atomNum]>0) && (!(R.contains(mol.getAtom(k)))) ) {
                                            if ( (AreEqual(GetName(mol,k),"N")) && (CountHydrogens(mol, k)==2)) {
                                                Branches++;
                                                Amine = true;
                                            }
                                        }
                                    }
                                    if ((Branches>0)&&(!Amine)) {
                                        InvalidStruct = true;
                                        break;
                                    }
                                }
                                if (AreEqual(GetName(mol,j),"N")) {
                                    for (int k=0; k<nAtoms; k++) {
                                        if ( (ConnMatrix[k][atomNum]>0) && (!(R.contains(mol.getAtom(k)))) ) {
                                            InvalidStruct = true;
                                            break;
                                        }
                                    }
                                    Pyridine = true;
                                }
                            }
                        }

                        if ( (!InvalidStruct) && (Pyridine||Amine) )
                            count += 0.5;
                    }

                } else {

                    // No cyclic structure, checks for AA

                    int NH2=0, C=0, R=0;
                    for (int k=0; k<nAtoms; k++)
                        if (ConnMatrix[k][i]>0) {
                            if (AreEqual(GetName(mol,k),"N"))
                                if (CountHydrogens(mol, k)==2)
                                    NH2++;
                                else
                                    R++;
                            else if (AreEqual(GetName(mol,k),"C"))
                                C++;
                            else
                                R++;
                        }
                    if (NH2==1)
                        if ( ((C==1)&&(R==1)) || (C==2) )
                            count += 1;

                }

            }

        }

        return count;
    }





    private String GetName(IAtomContainer mol, int atom) {
        return mol.getAtom(atom).getSymbol();
    }

    private boolean AreEqual(String AtomA, String AtomB){
        return AtomA.equalsIgnoreCase(AtomB);
    }

    private static int CountHydrogens(IAtomContainer mol, int atom) {

        int nH = 0;
        if(mol.getAtom(atom).getImplicitHydrogenCount() != null){
            nH = mol.getAtom(atom).getImplicitHydrogenCount();
        }
        return nH;
    }

    private static double[][] GetConnectionMatrix(IAtomContainer mol, boolean CheckAromaticity, boolean CheckCharges) {

        double[][] ConnMatrix = ConnectionMatrix.getMatrix(mol);


        if ( (!CheckAromaticity) && (!CheckCharges) )

            return ConnMatrix;

        else {

            for (int i=0; i<mol.getBondCount(); i++) {
                IAtom AtomA, AtomB;
                AtomA = mol.getBond(i).getAtom(0);
                AtomB = mol.getBond(i).getAtom(1);
                int A = mol.indexOf(AtomA);
                int B = mol.indexOf(AtomB);

                if (CheckAromaticity) {
                    if ((AtomA.getFlag(CDKConstants.ISAROMATIC)) &&
                            (AtomB.getFlag(CDKConstants.ISAROMATIC))) {

                        ConnMatrix[A][B] = 1.5;
                        ConnMatrix[B][A] = 1.5;
                    }
                }

                if (CheckCharges) {
                    if ((AtomA.getFormalCharge()!=0)&&(AtomB.getFormalCharge()!=0))
                        if ((AtomA.getFormalCharge()+AtomB.getFormalCharge())==0) {
                            ConnMatrix[A][B] += Math.abs(AtomA.getFormalCharge());
                            ConnMatrix[B][A] += Math.abs(AtomA.getFormalCharge());
                        }

                }
            }

            return ConnMatrix;
        }
    }
}
